### ISSUE TITLE
Unit test all of our Vue components

### ISSUE THREAD

**Issue by nylira** [tendermint/allinbits.com#9]
None of the Vue components on this website have unit tests. We can prevent a lot of broken content by requiring passing unit tests before pull requests can be accepted. 

- [ ] merge similar website components together across repos
- [ ] unit test every website component

### Related PRS
https://github.com/cosmos/cosmos.network/issues/181
https://github.com/tendermint/tendermint.com/issues/154
https://github.com/cosmos/voyager/issues/696

**Comment by jolesbi** [comment]
tests! for sure! do you have a sense of how many components aren't in voyager / will need additional tests?

**Comment by zramsay** [comment]
consolidating in https://github.com/tendermint/devops/issues/143
